### ISSUE TITLE
Doesn't seem to be working.

### ISSUE THREAD

**Issue by rocket-matt** [dylanowen/mdbook-graphviz#52] opened 2023-01-20 13:52 UTC
My book.toml files contains this:
```
[preprocessor.graphviz]
command = "mdbook-graphviz"
output-to-file = true
```
and my markdown file contains this:
```
'''dot process
digraph {
    "Instance" -> "Adapter"
}
'''
```
(Please note those quotes above are backticks in my files - just had to change them for markdown to work).

But the generated web page just shows the graphviz code and no diagram.

I have installed `mdbook-graphviz` and `graphviz`.

What am I doing wrong?

**Comment by dylanowen** [comment] 2023-01-31 14:40
Everything you've described sounds right. The build log from `RUST_LOG=debug mdbook build` or `RUST_LOG=trace mdbook build` might have more information? Alternatively if you have a sample project I could take a closer look.

**Comment by Cypher1** [comment] 2024-05-01 12:27
I'm going to close this assuming that it was affected by #56. If this issue can still be reproduced, please reopen it but we have heard anything since about a year ago.

**Closed by Cypher1** 2024-05-01 12:27 UTC
